=== kape1395/biosensor.solver-2D/xsd/Model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://lt.5grupe.karolis/biosensor/model"
    targetNamespace="http://lt.5grupe.karolis/biosensor/model"
    elementFormDefault="qualified">
    
    
    
    <xs:element name="model" type="Model"/>
    
    
    
    <xs:complexType name="Model">
        <xs:sequence>
            <xs:element name="substance"      type="Substance"      minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="reaction"       type="Reaction"       minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="medium"         type="Medium"         minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="area"           type="Area"           minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="boundCondition" type="BoundCondition" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="electrode"      type="Electrode"      minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="symbol"         type="Symbol"         minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="coordinateSystem" type="CoordinateSystem" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Substance">
        <xs:attribute name="name" type="SubstanceName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Reaction" abstract="true">
        <xs:attribute name="name" type="ReactionName"   use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Reaction_MichaelisMenten">
        <xs:complexContent>
            <xs:extension base="Reaction">
                <xs:attribute name="substrate" type="SubstanceName"  use="required"/>
                <xs:attribute name="product"   type="SubstanceName"  use="required"/>
                <xs:attribute name="V_max"     type="SymbolName"     use="required"/>
                <xs:attribute name="K_M"       type="SymbolName"     use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    
    
    <xs:complexType name="Medium">
        <xs:sequence>
            <xs:element name="diffusion" type="MediumDiffusion" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="reaction"  type="MediumReaction"  minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="MediumName" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="MediumDiffusion">
        <xs:attribute name="substance"   type="SubstanceName" use="required"/>
        <xs:attribute name="coefficient" type="SymbolName"    use="required"/>
    </xs:complexType>
    
    <xs:complexType name="MediumReaction">
        <xs:attribute name="reaction" type="ReactionName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Area">
        <xs:attribute name="top"    type="SymbolName" use="required"/>
        <xs:attribute name="bottom" type="SymbolName" use="required"/>
        <xs:attribute name="left"   type="SymbolName" use="required"/>
        <xs:attribute name="right"  type="SymbolName" use="required"/>
        <xs:attribute name="medium" type="MediumName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="BoundCondition" abstract="true">
        <xs:attribute name="from"      type="SymbolName"         use="required"/>
        <xs:attribute name="to"        type="SymbolName"         use="required"/>
        <xs:attribute name="at"        type="SymbolName"         use="required"/>
        <xs:attribute name="substance" type="SubstanceName"      use="required"/>
    </xs:complexType>
    
    <xs:complexType name="BoundCondition_Constant">
        <xs:complexContent>
            <xs:extension base="BoundCondition">
                <xs:attribute name="concentration" type="SymbolName" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="BoundCondition_Wall">
        <xs:complexContent>
            <xs:extension base="BoundCondition"/>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="BoundCondition_Merge">
        <xs:complexContent>
            <xs:extension base="BoundCondition"/>
        </xs:complexContent>
    </xs:complexType>
    
    
    
    <xs:complexType name="Electrode">
        <xs:sequence>
            <xs:element name="substrate" type="ElectrodeSubstrate"/>
            <xs:element name="position"  type="ElectrodePosition"/>
        </xs:sequence>
        <xs:attribute name="name" type="ElectrodeName" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="ElectrodeSubstrate">
        <xs:attribute name="substrate" type="SubstanceName" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="ElectrodePosition">
        <xs:attribute name="from"   type="SymbolName"   use="required"/>
        <xs:attribute name="to"     type="SymbolName"   use="required"/>
        <xs:attribute name="at"     type="SymbolName"   use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Symbol">
        <xs:attribute name="name"       type="SymbolName" use="required"/>
        <xs:attribute name="value"      type="xs:double"  use="required"/>
        <xs:attribute name="dimension"  type="xs:string"  use="optional"/>
    </xs:complexType>
    
    
    <xs:simpleType name="CoordinateSystem">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Cartesian"/>
            <xs:enumeration value="Cylindrical"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="SubstanceName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="ReactionName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="MediumName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="ElectrodeName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="SymbolName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
</xs:schema>

=== kape1395/biosensor.solver-2D/xsd/Model.xml
<?xml version="1.0" encoding="UTF-8"?>
<model
    xmlns="http://lt.5grupe.karolis/biosensor/model"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://lt.5grupe.karolis/biosensor/model Model.xsd"
    coordinateSystem="Cartesian">
    
    <substance name="S"/>
    <substance name="P"/>
    
    <reaction xsi:type="Reaction_MichaelisMenten"
        name="E"
        substrate="S"
        product="P"
        V_max="V_max"
        K_M="K_M"
    />
    
    
    <medium name="Enzyme">
        <diffusion substance="S" coefficient="D_Enz_S"/>
        <diffusion substance="P" coefficient="D_Enz_P"/>
        <reaction reaction="R1"/>
    </medium>
    <medium name="PerforatedMembrane">
    </medium>
    <medium name="SelectiveMembrane">
        <diffusion substance="P" coefficient="D_Sel_P"/>
    </medium>
    
    
    <area top="y1" bottom="y2" left="x1" right="x2" medium="Enzyme"/>
    <area top="y2" bottom="y3" left="x1" right="x3" medium="Enzyme"/>
    <area top="y1" bottom="y2" left="x2" right="x3" medium="PerforatedMembrane"/>
    <area top="y3" bottom="y4" left="x1" right="x3" medium="SelectiveMembrane"/>
    
    
    <boundCondition from="x1" to="x1" at="y1" substance="S" xsi:type="BoundCondition_Constant" concentration="S_0"/>
    <boundCondition from="x1" to="x1" at="y1" substance="P" xsi:type="BoundCondition_Constant" concentration="P_0"/>
    <boundCondition from="y1" to="y3" at="x1" substance="S" xsi:type="BoundCondition_Wall"/>
    <boundCondition from="y1" to="y4" at="x1" substance="P" xsi:type="BoundCondition_Wall"/>
    <boundCondition from="y2" to="y3" at="x3" substance="S" xsi:type="BoundCondition_Wall"/>
    <boundCondition from="y2" to="y4" at="x3" substance="P" xsi:type="BoundCondition_Wall"/>
    <boundCondition from="x1" to="x3" at="y4" substance="P" xsi:type="BoundCondition_Constant" concentration="E_0"/>
    
    <electrode name="Electrode">
        <substrate substrate="P"/>
        <position from="x1" to="x3" at="y4"/>
    </electrode>
    
    <symbol name="S_0"      value="7.5E-7"  dimension="mol/cm^2"/>
    <symbol name="P_0"      value="0.0"     dimension="mol/cm^2"/>
    <symbol name="E_0"      value="0.0"     dimension="mol/cm^2"/>
    <symbol name="V_max"    value="1E-8"    dimension="mol/s"/>
    <symbol name="K_M"      value="1E-8"    />
    <symbol name="D_Enz_S"  value="1E-6"    dimension="m^2/s"/>
    <symbol name="D_Enz_P"  value="1E-6"    dimension="m^2/s"/>
    <symbol name="D_Sel_P"  value="1E-6"    dimension="m^2/s"/>
    <symbol name="x1"       value="0.0"     dimension="m"/>
    <symbol name="x2"       value="1.0E-5"  dimension="m"/>
    <symbol name="x3"       value="1.01E-3" dimension="m"/>
    <symbol name="y1"       value="0.0"     dimension="m"/>
    <symbol name="y2"       value="1.0E-3"  dimension="m"/>
    <symbol name="y3"       value="1.2E-3"  dimension="m"/>
    <symbol name="y4"       value="1.4E-3"  dimension="m"/>
</model>
