=== kape1395/biosensor.solver-2D/src/libbiosensor-xml/Model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    targetNamespace ="http://lt.5grupe.karolis/biosensor/model"
    xmlns           ="http://lt.5grupe.karolis/biosensor/model"
    xmlns:xs        ="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    
    
    
    <xs:element name="model" type="Model"/>
    
    
    
    <xs:complexType name="Model">
        <xs:sequence>
            <xs:element name="axis"         type="Axis"         minOccurs="1" maxOccurs="2"/>
            <xs:element name="substance"    type="Substance"    minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="medium"       type="Medium"       minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="bound"        type="Bound"        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="transducer"   type="Transducer"   minOccurs="0" maxOccurs="1"/>
            <xs:element name="symbol"       type="Symbol"       minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="solver"       type="Solver"       minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="coordinateSystem" type="CoordinateSystem" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Axis">
        <xs:sequence>
            <xs:element name="point" type="AxisPoint" minOccurs="2" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="AxisName" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="AxisPoint">
        <xs:attribute name="position" type="SymbolName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Substance">
        <xs:attribute name="name" type="SubstanceName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Medium">
        <xs:sequence>
            <xs:element name="substance" type="MediumSubstance" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="reaction"  type="MediumReaction"  minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="area"      type="MediumArea"      minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="MediumName" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="MediumSubstance">
        <xs:attribute name="name"       type="SubstanceName" use="required"/>
        <xs:attribute name="diffusion"  type="SymbolName"    use="optional"/>
        <xs:attribute name="initial"    type="SymbolName"    use="required"/>
    </xs:complexType>
    
    <xs:complexType name="MediumReaction" abstract="true">
    </xs:complexType>
    
    <xs:complexType name="MediumArea">
        <xs:attribute name="top"    type="SymbolName" use="optional"/>
        <xs:attribute name="bottom" type="SymbolName" use="optional"/>
        <xs:attribute name="left"   type="SymbolName" use="optional"/>
        <xs:attribute name="right"  type="SymbolName" use="optional"/>
        <xs:attribute name="from"   type="SymbolName" use="optional"/>
        <xs:attribute name="to"     type="SymbolName" use="optional"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Bound">
        <xs:sequence>
            <xs:element name="substance" type="BoundSubstance" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name"   type="BoundName"    use="optional"/>
        <xs:attribute name="from"   type="SymbolName"   use="optional"/>
        <xs:attribute name="to"     type="SymbolName"   use="optional"/>
        <xs:attribute name="at"     type="SymbolName"   use="required"/>
    </xs:complexType>
    
    <xs:complexType name="BoundSubstance" abstract="true">
        <xs:attribute name="name" type="SubstanceName" use="required"/>
    </xs:complexType>
    
    

    <xs:complexType name="Transducer" abstract="true">
        <xs:attribute name="name" type="TransducerName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Symbol">
        <xs:attribute name="name"       type="SymbolName" use="required"/>
        <xs:attribute name="value"      type="xs:double"  use="required"/>
        <xs:attribute name="dimension"  type="xs:string"  use="optional"/>
    </xs:complexType>
    
    
    <xs:complexType name="Solver" abstract="true">
        <xs:sequence>
            <xs:element name="output" type="SolverOutput" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SolverOutput" abstract="true">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    

    <xs:simpleType name="CoordinateSystem">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Cartesian"/>
            <xs:enumeration value="Cylindrical"/>
            <xs:enumeration value="Linear"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="SubstanceName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="MediumName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="AxisName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="BoundName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="TransducerName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="SymbolName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
</xs:schema>

=== kape1395/biosensor.solver-2D/test/test-1100-cyl-perforated_membrane.xml
<?xml version="1.0" encoding="UTF-8"?>
<model
    xmlns  ="http://lt.5grupe.karolis/biosensor/model"
    xmlns:b="http://lt.5grupe.karolis/biosensor/model/bound"
    xmlns:r="http://lt.5grupe.karolis/biosensor/model/reaction"
    xmlns:s="http://lt.5grupe.karolis/biosensor/model/solver"
    xmlns:l="http://lt.5grupe.karolis/biosensor/model/listener"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://lt.5grupe.karolis/biosensor/model          ../src/libbiosensor-xml/Model.xsd
                        http://lt.5grupe.karolis/biosensor/model/bound    ../src/libbiosensor-xml/ModelBound.xsd
                        http://lt.5grupe.karolis/biosensor/model/reaction ../src/libbiosensor-xml/ModelReaction.xsd
                        http://lt.5grupe.karolis/biosensor/model/solver   ../src/libbiosensor-xml/ModelSolver.xsd
                        http://lt.5grupe.karolis/biosensor/model/listener ../src/libbiosensor-xml/ModelListener.xsd"
    coordinateSystem="Cylindrical">


    <axis name="r">
        <point position="r0"/>
        <point position="r1"/>
        <point position="r2"/>
    </axis>
    <axis name="z">
        <point position="z0"/>
        <point position="z1"/>
        <point position="z2"/>
        <point position="z3"/>
        <point position="z4"/>
    </axis>


    <substance name="S"/>
    <substance name="P"/>


    <medium name="Omega_1">
        <substance name="P" diffusion="D_1" initial="0"/>
        <area top="z1" bottom="z0" left="r0" right="r2"/>
    </medium>
    <medium name="Omega_2">
        <substance name="S" diffusion="D_2" initial="0"/>
        <substance name="P" diffusion="D_2" initial="0"/>
        <reaction xsi:type="r:MichaelisMenten" V_max="V_max" K_M="K_M" substrate="S" product="P"/>
        <area top="z1" bottom="z2" left="r0" right="r2"/>
        <area top="z2" bottom="z3" left="r0" right="r1"/>
    </medium>
    <medium name="Omega_3">
        <substance name="S" diffusion="D_3" initial="0"/>
        <substance name="P" diffusion="D_3" initial="0"/>
        <area top="z3" bottom="z4" left="r0" right="r1"/>
    </medium>
    <medium name="Omega_3">
        <area top="z2" bottom="z4" left="r1" right="r2"/>
    </medium>


    <bound from="r0" to="r2" at="z0">
        <substance name="P" xsi:type="b:Constant" concentration="0"/>
    </bound>
    <bound from="r0" to="r1" at="z4">
        <substance name="S" xsi:type="b:Constant" concentration="S_0"/>
        <substance name="P" xsi:type="b:Constant" concentration="0"/>
    </bound>


    <!-- Geometry -->
    <symbol name="r0"   value="0.0"     dimension="m"/>
    <symbol name="r1"   value="1.0E-7"  dimension="m"/>
    <symbol name="r2"   value="1.0E-6"  dimension="m"/>
    <symbol name="z0"   value="0.0"     dimension="m"/>
    <symbol name="z1"   value="2.0E-6"  dimension="m"/>
    <symbol name="z2"   value="4.0E-6"  dimension="m"/>
    <symbol name="z3"   value="9.0E-6"  dimension="m"/>
    <symbol name="z4"   value="1.4E-5"  dimension="m"/>

    <!-- Diffusion coefficients -->
    <symbol name="D_1"  value="1E-6"    dimension="m^2/s"/>
    <symbol name="D_2"  value="3E-4"    dimension="m^2/s"/>
    <symbol name="D_3"  value="6E-4"    dimension="m^2/s"/>

    <!-- Concentrations -->
    <symbol name="S_0"  value="3.3E-3"  dimension="M"/>
    <symbol name="0"    value="0.0"     dimension="M"/>

    <!-- Reaction parameters -->
    <symbol name="V_max"  value="1E-5"  dimension="M/s"/>
    <symbol name="K_M"    value="1E-4"  dimension="M"/>

    
    <solver xsi:type="s:Implicit2D" timeStep="1E-4">
        <s:axis from="r0" to="r1" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="r1" to="r2" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="z0" to="z1" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="z1" to="z2" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="z2" to="z3" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="z3" to="z4" xsi:type="s:ConstantAxisPart" stepCount="200"/>
    </solver>

</model>

=== kape1395/biosensor.solver-2D/test/test-0300-car-redox_wo_diff.xml
<?xml version="1.0" encoding="UTF-8"?>
<model
    xmlns  ="http://lt.5grupe.karolis/biosensor/model"
    xmlns:b="http://lt.5grupe.karolis/biosensor/model/bound"
    xmlns:r="http://lt.5grupe.karolis/biosensor/model/reaction"
    xmlns:s="http://lt.5grupe.karolis/biosensor/model/solver"
    xmlns:t="http://lt.5grupe.karolis/biosensor/model/transducer"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        http://lt.5grupe.karolis/biosensor/model            ../src/libbiosensor-xml/Model.xsd
        http://lt.5grupe.karolis/biosensor/model/bound      ../src/libbiosensor-xml/ModelBound.xsd
        http://lt.5grupe.karolis/biosensor/model/reaction   ../src/libbiosensor-xml/ModelReaction.xsd
        http://lt.5grupe.karolis/biosensor/model/solver     ../src/libbiosensor-xml/ModelSolver.xsd
        http://lt.5grupe.karolis/biosensor/model/transducer ../src/libbiosensor-xml/ModelTransducer.xsd
        "
    coordinateSystem="Cartesian">


    <axis name="x">
        <point position="x_0"/>
        <point position="x_1"/>
    </axis>
    <axis name="y">
        <point position="y_0"/>
        <point position="y_1"/>
    </axis>


    <substance name="S_1"/>
    <substance name="S_2"/>
    <substance name="P_1"/>
    <substance name="P_2"/>


    <medium name="\Omega_1">
        <substance name="S_1" diffusion="D_0" initial="S_0"/>
        <substance name="S_2" diffusion="D_0" initial="S_0"/>
        <substance name="P_1" diffusion="D_0" initial="0"/>
        <substance name="P_2" diffusion="D_0" initial="0"/>
        <reaction xsi:type="r:ReductionOxidation" rate="k_1">
            <r:substrate name="S_1"/>
            <r:substrate name="S_2"/>
            <r:product name="P_1"/>
            <r:product name="P_2"/>
        </reaction>
        <area top="y_1" bottom="y_0" left="x_0" right="x_1"/>
    </medium>

    <bound at="x_0" from="y_0" to="y_1">
        <substance name="S_1" xsi:type="b:Wall"/>
        <substance name="S_2" xsi:type="b:Wall"/>
        <substance name="P_1" xsi:type="b:Wall"/>
        <substance name="P_2" xsi:type="b:Wall"/>
    </bound>
    <bound at="x_1" from="y_0" to="y_1">
        <substance name="S_1" xsi:type="b:Wall"/>
        <substance name="S_2" xsi:type="b:Wall"/>
        <substance name="P_1" xsi:type="b:Wall"/>
        <substance name="P_2" xsi:type="b:Wall"/>
    </bound>
    <bound at="y_0" from="x_0" to="x_1">
        <substance name="S_1" xsi:type="b:Wall"/>
        <substance name="S_2" xsi:type="b:Wall"/>
        <substance name="P_1" xsi:type="b:Wall"/>
        <substance name="P_2" xsi:type="b:Wall"/>
    </bound>
    <bound at="y_1" from="x_0" to="x_1">
        <substance name="S_1" xsi:type="b:Wall"/>
        <substance name="S_2" xsi:type="b:Wall"/>
        <substance name="P_1" xsi:type="b:Wall"/>
        <substance name="P_2" xsi:type="b:Wall"/>
    </bound>
    
    <!-- Geometry -->
    <symbol name="x_0" value="0.0" dimension="m"/>
    <symbol name="x_1" value="1.0" dimension="m"/>
    <symbol name="y_0" value="0.0" dimension="m"/>
    <symbol name="y_1" value="1.0" dimension="m"/>


    <!-- Concentrations -->
    <symbol name="S_0" value="1.0E2"  dimension="mol / m^3"/>
    <symbol name="0"   value="0.0"    dimension="mol / m^3"/>

    <!-- Reaction rates -->
    <symbol name="k_1" value="1E7"  dimension="mol / m^3 s"/>

    <!-- -->
    <symbol name="D_0"  value="1.0" dimension="m^2 / s"/>



    <solver xsi:type="s:Implicit2D" timeStep="1E-11">
        <output name="kinetic" xsi:type="s:Kinetic" stepCount="1">
            <s:output name="concentrations" xsi:type="s:ConcentrationProfile"/>
        </output>
        <s:axis from="x_0" to="x_1" xsi:type="s:ConstantAxisPart" stepCount="100"/>
        <s:axis from="y_0" to="y_1" xsi:type="s:ConstantAxisPart" stepCount="100"/>
        <s:stopCondition xsi:type="s:FailIfAbove" stepCount="1000"/>
    </solver>

</model>

=== kape1395/biosensor.solver-2D/test/test-0051_car-trivial_horizontal.xml
<?xml version="1.0" encoding="UTF-8"?>
<model
    xmlns  ="http://lt.5grupe.karolis/biosensor/model"
    xmlns:b="http://lt.5grupe.karolis/biosensor/model/bound"
    xmlns:r="http://lt.5grupe.karolis/biosensor/model/reaction"
    xmlns:s="http://lt.5grupe.karolis/biosensor/model/solver"
    xmlns:l="http://lt.5grupe.karolis/biosensor/model/listener"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://lt.5grupe.karolis/biosensor/model          ../src/libbiosensor-xml/Model.xsd
                        http://lt.5grupe.karolis/biosensor/model/bound    ../src/libbiosensor-xml/ModelBound.xsd
                        http://lt.5grupe.karolis/biosensor/model/reaction ../src/libbiosensor-xml/ModelReaction.xsd
                        http://lt.5grupe.karolis/biosensor/model/solver   ../src/libbiosensor-xml/ModelSolver.xsd
                        http://lt.5grupe.karolis/biosensor/model/listener ../src/libbiosensor-xml/ModelListener.xsd"
    coordinateSystem="Cartesian">


    <axis name="x">
        <point position="x0"/>
        <point position="x1"/>
    </axis>
    <axis name="y">
        <point position="y0"/>
        <point position="y1"/>
    </axis>


    <substance name="S"/>


    <medium name="Diffusion">
        <substance name="S" diffusion="D_Diff_S" initial="0"/>
        <area top="y0" bottom="y1" left="x0" right="x1"/>
    </medium>

    <bound from="y0" to="y1" at="x0">
        <substance name="S" xsi:type="b:Constant" concentration="S_0"/>
    </bound>
    <bound from="y0" to="y1" at="x1">
        <substance name="S" xsi:type="b:Constant" concentration="0"/>
    </bound>



    <!-- Geometry -->
    <symbol name="x0"       value="0.0"     dimension="m"/>
    <symbol name="x1"       value="1.0E-3"  dimension="m"/>
    <symbol name="y0"       value="0.0"     dimension="m"/>
    <symbol name="y1"       value="1.0E-3"  dimension="m"/>
    <symbol name="D_Diff_S" value="1E-6"    dimension="m^2/s"/>
    <symbol name="S_0"      value="1E-8"    dimension="mol/cm^2"/>
    <symbol name="0"        value="0.0"     dimension="mol/cm^2"/>


    <solver xsi:type="s:Implicit2D" timeStep="1E-4">
        <s:axis from="x0" to="x1" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="y0" to="y1" xsi:type="s:ConstantAxisPart" stepCount="200"/>
    </solver>

</model>

=== kape1395/biosensor.solver-2D/src/bio_ers/test/bio_ers_model_tests-CNT-1D.xml
<?xml version="1.0" encoding="UTF-8"?>
<model
    xmlns  ="http://karolis.5grupe.lt/biosensor/model"
    xmlns:b="http://karolis.5grupe.lt/biosensor/model/bound"
    xmlns:r="http://karolis.5grupe.lt/biosensor/model/reaction"
    xmlns:s="http://karolis.5grupe.lt/biosensor/model/solver"
    xmlns:t="http://karolis.5grupe.lt/biosensor/model/transducer"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        http://karolis.5grupe.lt/biosensor/model            /usr/share/biosensor/Model.xsd
        http://karolis.5grupe.lt/biosensor/model/bound      /usr/share/biosensor/ModelBound.xsd
        http://karolis.5grupe.lt/biosensor/model/reaction   /usr/share/biosensor/ModelReaction.xsd
        http://karolis.5grupe.lt/biosensor/model/solver     /usr/share/biosensor/ModelSolver.xsd
        http://karolis.5grupe.lt/biosensor/model/transducer /usr/share/biosensor/ModelTransducer.xsd
        "
    coordinateSystem="Cartesian">


    <axis name="x">
        <point position="x_0"/>
        <point position="x_1"/>
    </axis>
    <axis name="y">
        <point position="z_0"/>
        <point position="z_1"/>
        <point position="z_2"/>
        <point position="z_3"/>
        <point position="z_4"/>
    </axis>


    <substance name="S"/>
    <substance name="E_{ox}"/>
    <substance name="E_{red}"/>
    <substance name="M_{ox}"/>
    <substance name="M_{red}"/>


    <reaction name="R_1" xsi:type="r:ReductionOxidation" rate="k_1">
        <r:substrate name="E_{ox}"/>
        <r:substrate name="S"/>
        <r:product name="E_{red}"/>
    </reaction>
    <reaction name="R_2" xsi:type="r:ReductionOxidation" rate="k_2">
        <r:substrate name="E_{red}"/>
        <r:substrate name="M_{ox}"/>
        <r:product name="E_{ox}"/>
        <r:product name="M_{red}"/>
    </reaction>
    <reaction name="R_2b" xsi:type="r:ReductionOxidation" rate="k_2">
        <r:substrate name="E_{red}"/>
        <r:substrate name="M_{ox}"/>
        <r:product name="E_{ox}"/>
        <r:product name="M_{ox}"/>
    </reaction>
    <reaction name="R_3" xsi:type="r:ReductionOxidation" rate="k_3">
        <r:substrate name="M_{red}"/>
        <r:product name="M_{ox}"/>
    </reaction>


    <medium name="\Omega_1">
        <substance name="S"         diffusion="D_1" initial="0"/>
        <substance name="E_{ox}"                    initial="E_0"/>
        <substance name="E_{red}"                   initial="0"/>
        <substance name="M_{ox}"    diffusion="D_1" initial="0"/>
        <substance name="M_{red}"   diffusion="D_1" initial="0"/>
        <reaction name="R_1"/>
        <reaction name="R_2"/>
        <area top="z_0" bottom="z_1" left="x_0" right="x_1"/>
    </medium>
    <medium name="\Omega_2">
        <substance name="S"         diffusion="D_2" initial="0"/>
        <substance name="E_{ox}"                    initial="E_1"/>
        <substance name="E_{red}"                   initial="0"/>
        <substance name="M_{ox}"    diffusion="D_2" initial="0"/>
        <reaction name="R_1"/>
        <reaction name="R_2b"/>
        <area top="z_1" bottom="z_2" left="x_0" right="x_1"/>
    </medium>
    <medium name="\Omega_3">
        <substance name="S"         diffusion="D_3" initial="0"/>
        <substance name="M_{ox}"    diffusion="D_3" initial="0"/>
        <area top="z_2" bottom="z_3" left="x_0" right="x_1"/>
    </medium>
    <medium name="\Omega_4">
        <substance name="S"         diffusion="D_4" initial="0"/>
        <substance name="M_{ox}"    diffusion="D_4" initial="0"/>
        <area top="z_3" bottom="z_4" left="x_0" right="x_1"/>
    </medium>


    <bound from="x_0" to="x_1" at="z_4" name="ExternalBound">
        <substance name="S"       xsi:type="b:Constant" concentration="S_0"/>
        <substance name="M_{ox}"  xsi:type="b:Constant" concentration="M_0"/>
    </bound>
    <bound from="x_0" to="x_1" at="z_1" name="BoundBetweenEnzymes">
        <substance name="M_{red}" xsi:type="b:Constant" concentration="0"/>
        <reaction name="R_3"/>
    </bound>


    <transducer name="electrode" xsi:type="t:CompositeElectrode">
        <t:transducer
            name="injectedElectrode"
            xsi:type="t:InjectedElectrode"
            medium="\Omega_2"
            reaction="R_2b"
        />
        <t:transducer
            name="streamElectrode"
            xsi:type="t:AmperometricElectrode"
            bound="BoundBetweenEnzymes"
            substance="M_{red}"
        />
    </transducer>


    <!-- Geometry -->
    <symbol name="x_0" value="0.0"      dimension="m"/>
    <symbol name="x_1" value="1.0"      dimension="m"/>
    <symbol name="z_0" value="0.0"      dimension="m"/>
    <symbol name="z_1" value="0.001E-4" dimension="m"/>
    <symbol name="z_2" value="0.005E-4" dimension="m"/>
    <symbol name="z_3" value="0.105E-4" dimension="m"/>
    <symbol name="z_4" value="1.605E-4" dimension="m"/>

    <!-- Diffusion coefficients, see bio.erl -->
    <symbol name="D_1" value="3.000E-10"  dimension="m^2/s"/>
    <symbol name="D_2" value="1.500E-10"  dimension="m^2/s"/>
    <symbol name="D_3" value="1.875E-11"  dimension="m^2/s"/>
    <symbol name="D_4" value="6.000E-10"  dimension="m^2/s"/>

    <!-- Concentrations -->
    <symbol name="E_0" value="4.55E-2"  dimension="mol/m^3"/>
    <symbol name="E_1" value="2.275E-2" dimension="mol/m^3"/>
    <symbol name="M_0" value="5.0E-2" dimension="mol/m^3"/>
    <symbol name="S_0" value="5.0"    dimension="mol/m^3"/>
    <symbol name="0"   value="0.0"    dimension="mol/m^3"/>

    <!-- Reaction rates -->
    <symbol name="k_1" value="6.9E2" dimension="m^3/mol*s"/>
    <symbol name="k_2" value="6.9E4" dimension="m^3/mol*s"/>
    <symbol name="k_3" value="INF"   dimension="m^3/mol*s"/>


    <solver xsi:type="s:Implicit1D" timeStep="1E-5">
        <output name="response" xsi:type="s:Kinetic" stepCount="1000">
            <s:output name="currentDensity"     xsi:type="s:CurrentDensity"/>
        </output>
        <output name="substanceConcentrations" xsi:type="s:Kinetic" stepCount="10000">
            <s:output name="concentrations"     xsi:type="s:ConcentrationProfile" precision="12"/>
            <s:output name="avgConcentrations"  xsi:type="s:AveragedConcentration"/>
            <s:output name="avgConcInOmega_1"   xsi:type="s:AveragedConcentration" medium="\Omega_1"/>
            <s:output name="avgConcInOmega_2"   xsi:type="s:AveragedConcentration" medium="\Omega_2"/>
            <s:output name="avgConcInOmega_3"   xsi:type="s:AveragedConcentration" medium="\Omega_3"/>
            <s:output name="avgConcInOmega_4"   xsi:type="s:AveragedConcentration" medium="\Omega_4"/>
        </output>
        <s:axis from="x_0" to="x_1" xsi:type="s:ConstantAxisPart" stepCount="2"/>
        <s:axis from="z_0" to="z_1" xsi:type="s:ConstantAxisPart" stepCount="50"/>
        <s:axis from="z_1" to="z_2" xsi:type="s:ConstantAxisPart" stepCount="50"/>
        <s:axis from="z_2" to="z_3" xsi:type="s:ConstantAxisPart" stepCount="50"/>
        <s:axis from="z_3" to="z_4" xsi:type="s:ConstantAxisPart" stepCount="50"/>
        <s:stopCondition
            xsi:type="s:StopConditionValidAfter"
            stepCount="100000">
            <s:stopCondition
                xsi:type="s:CurrentDensityGradient"
                lessThan="0.01"
                normalized="true"
            />
        </s:stopCondition>
        <s:stopCondition xsi:type="s:FailIfAbove" stepCount="500000000"/>
        <s:stopCondition xsi:type="s:FailIfInvalidConcentrations"/>
        <s:stopCondition
            xsi:type="s:FailISumOfConcentrationsNonConst"
            medium="\Omega_1" sum="E_0" error="1E-6">
            <s:substance>E_{ox}</s:substance>
            <s:substance>E_{red}</s:substance>
        </s:stopCondition>
        <s:stopCondition
            xsi:type="s:FailISumOfConcentrationsNonConst"
            medium="\Omega_2" sum="E_1" error="1E-6">
            <s:substance>E_{ox}</s:substance>
            <s:substance>E_{red}</s:substance>
        </s:stopCondition>
    </solver>

</model>
