=== kape1395/biosensor.solver-2D/src/libbiosensor-xml/Model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    targetNamespace ="http://lt.5grupe.karolis/biosensor/model"
    xmlns           ="http://lt.5grupe.karolis/biosensor/model"
    xmlns:xs        ="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    
    
    
    <xs:element name="model" type="Model"/>
    
    
    
    <xs:complexType name="Model">
        <xs:sequence>
            <xs:element name="axis"         type="Axis"         minOccurs="1" maxOccurs="2"/>
            <xs:element name="substance"    type="Substance"    minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="medium"       type="Medium"       minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="bound"        type="Bound"        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="transducer"   type="Transducer"   minOccurs="0" maxOccurs="1"/>
            <xs:element name="symbol"       type="Symbol"       minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="solver"       type="Solver"       minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="coordinateSystem" type="CoordinateSystem" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Axis">
        <xs:sequence>
            <xs:element name="point" type="AxisPoint" minOccurs="2" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="AxisName" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="AxisPoint">
        <xs:attribute name="position" type="SymbolName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Substance">
        <xs:attribute name="name" type="SubstanceName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Medium">
        <xs:sequence>
            <xs:element name="substance" type="MediumSubstance" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="reaction"  type="MediumReaction"  minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="area"      type="MediumArea"      minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="MediumName" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="MediumSubstance">
        <xs:attribute name="name"       type="SubstanceName" use="required"/>
        <xs:attribute name="diffusion"  type="SymbolName"    use="optional"/>
        <xs:attribute name="initial"    type="SymbolName"    use="required"/>
    </xs:complexType>
    
    <xs:complexType name="MediumReaction" abstract="true">
    </xs:complexType>
    
    <xs:complexType name="MediumArea">
        <xs:attribute name="top"    type="SymbolName" use="optional"/>
        <xs:attribute name="bottom" type="SymbolName" use="optional"/>
        <xs:attribute name="left"   type="SymbolName" use="optional"/>
        <xs:attribute name="right"  type="SymbolName" use="optional"/>
        <xs:attribute name="from"   type="SymbolName" use="optional"/>
        <xs:attribute name="to"     type="SymbolName" use="optional"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Bound">
        <xs:sequence>
            <xs:element name="substance" type="BoundSubstance" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name"   type="BoundName"    use="optional"/>
        <xs:attribute name="from"   type="SymbolName"   use="optional"/>
        <xs:attribute name="to"     type="SymbolName"   use="optional"/>
        <xs:attribute name="at"     type="SymbolName"   use="required"/>
    </xs:complexType>
    
    <xs:complexType name="BoundSubstance" abstract="true">
        <xs:attribute name="name" type="SubstanceName" use="required"/>
    </xs:complexType>
    
    

    <xs:complexType name="Transducer" abstract="true">
        <xs:attribute name="name" type="TransducerName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Symbol">
        <xs:attribute name="name"       type="SymbolName" use="required"/>
        <xs:attribute name="value"      type="xs:double"  use="required"/>
        <xs:attribute name="dimension"  type="xs:string"  use="optional"/>
    </xs:complexType>
    
    
    <xs:complexType name="Solver" abstract="true">
        <xs:sequence>
            <xs:element name="output" type="SolverOutput" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SolverOutput" abstract="true">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    

    <xs:simpleType name="CoordinateSystem">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Cartesian"/>
            <xs:enumeration value="Cylindrical"/>
            <xs:enumeration value="Linear"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="SubstanceName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="MediumName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="AxisName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="BoundName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="TransducerName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="SymbolName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
</xs:schema>

=== kape1395/biosensor.solver-2D/test/test-2100-nano2d-hiR-dt4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<model
    xmlns  ="http://karolis.5grupe.lt/biosensor/model"
    xmlns:b="http://karolis.5grupe.lt/biosensor/model/bound"
    xmlns:r="http://karolis.5grupe.lt/biosensor/model/reaction"
    xmlns:s="http://karolis.5grupe.lt/biosensor/model/solver"
    xmlns:t="http://karolis.5grupe.lt/biosensor/model/transducer"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        http://karolis.5grupe.lt/biosensor/model            /usr/share/biosensor/Model.xsd
        http://karolis.5grupe.lt/biosensor/model/bound      /usr/share/biosensor/ModelBound.xsd
        http://karolis.5grupe.lt/biosensor/model/reaction   /usr/share/biosensor/ModelReaction.xsd
        http://karolis.5grupe.lt/biosensor/model/solver     /usr/share/biosensor/ModelSolver.xsd
        http://karolis.5grupe.lt/biosensor/model/transducer /usr/share/biosensor/ModelTransducer.xsd
        "
    coordinateSystem="Cylindrical">

  <axis name="r">
    <point position="r_0"/>
    <point position="r_1"/>
    <point position="r_2"/>
  </axis>

  <axis name="z">
    <point position="z_0"/>
    <point position="z_1"/>
    <point position="z_2"/>
    <point position="z_3"/>
    <point position="z_4"/>
  </axis>

  <substance name="S"/>

  <substance name="E_{ox}"/>

  <substance name="E_{red}"/>

  <substance name="M_{ox}"/>

  <substance name="M_{red}"/>

  <reaction name="R_1" rate="k_1" xsi:type="r:ReductionOxidation">
    <r:substrate coefficient="1" name="E_{ox}"/>
    <r:substrate coefficient="1" name="S"/>
    <r:product coefficient="1" name="E_{red}"/>
  </reaction>

  <reaction name="R_2" rate="k_2" xsi:type="r:ReductionOxidation">
    <r:substrate coefficient="1" name="E_{red}"/>
    <r:substrate coefficient="1" name="M_{ox}"/>
    <r:product coefficient="1" name="E_{ox}"/>
    <r:product coefficient="1" name="M_{red}"/>
  </reaction>

  <reaction name="R_2b" rate="k_2" xsi:type="r:ReductionOxidation">
    <r:substrate coefficient="1" name="E_{red}"/>
    <r:substrate coefficient="1" name="M_{ox}"/>
    <r:product coefficient="1" name="E_{ox}"/>
    <r:product coefficient="1" name="M_{ox}"/>
  </reaction>

  <reaction name="R_3" rate="k_3" xsi:type="r:ReductionOxidation">
    <r:substrate coefficient="1" name="M_{red}"/>
    <r:product coefficient="1" name="M_{ox}"/>
  </reaction>

  <medium name="\Omega_1">
    <substance diffusion="D_1" initial="0" name="S"/>
    <substance initial="E_0" name="E_{ox}"/>
    <substance initial="0" name="E_{red}"/>
    <substance diffusion="D_1" initial="0" name="M_{ox}"/>
    <substance diffusion="D_1" initial="0" name="M_{red}"/>
    <reaction name="R_1"/>
    <reaction name="R_2"/>
    <area bottom="z_1" left="r_0" right="r_2" top="z_0"/>
  </medium>

  <medium diffusionRatio="alpha" name="\Omega_2">
    <substance diffusion="D_2" initial="0" name="S"/>
    <substance initial="E_1" name="E_{ox}"/>
    <substance initial="0" name="E_{red}"/>
    <substance diffusion="D_2" initial="0" name="M_{ox}"/>
    <reaction name="R_1"/>
    <reaction name="R_2b"/>
    <area bottom="z_2" left="r_0" right="r_2" top="z_1"/>
  </medium>

  <medium diffusionRatio="alpha" name="\Omega_3">
    <substance diffusion="D_3" initial="0" name="S"/>
    <substance diffusion="D_3" initial="0" name="M_{ox}"/>
    <area bottom="z_3" left="r_0" right="r_1" top="z_2"/>
  </medium>

  <medium name="\Omega_4">
    <substance diffusion="D_4" initial="0" name="S"/>
    <substance diffusion="D_4" initial="0" name="M_{ox}"/>
    <area bottom="z_4" left="r_0" right="r_2" top="z_3"/>
  </medium>

  <bound at="z_4" from="r_0" name="ExternalBound" to="r_2">
    <substance concentration="S_0" name="S" xsi:type="b:Constant"/>
    <substance concentration="M_0" name="M_{ox}" xsi:type="b:Constant"/>
  </bound>

  <bound at="z_1" from="r_0" name="BoundBetweenEnzymes" to="r_2">
    <substance concentration="0" name="M_{red}" xsi:type="b:Constant"/>
    <reaction name="R_3"/>
  </bound>

  <transducer name="electrode" xsi:type="t:CompositeElectrode">
    <t:transducer medium="\Omega_2" name="injectedElectrode" reaction="R_2b" xsi:type="t:InjectedElectrode"/>
    <t:transducer bound="BoundBetweenEnzymes" name="streamElectrode" substance="M_{red}" xsi:type="t:AmperometricElectrode"/>
  </transducer>

  <symbol dimension="m" name="r_0" value="0"/>

  <symbol dimension="m" name="r_1" value="0.0000002"/>

  <symbol dimension="m" name="r_2" value="0.0000008"/>

  <symbol dimension="m" name="z_0" value="0"/>

  <symbol dimension="m" name="z_1" value="0.001"/>

  <symbol dimension="m" name="z_2" value="0.0010004"/>

  <symbol dimension="m" name="z_3" value="0.0010104"/>

  <symbol dimension="m" name="z_4" value="0.0011604"/>

  <symbol dimension="m^2/s" name="D_1" value="0.0000000003"/>

  <symbol dimension="m^2/s" name="D_2" value="0.000000000075"/>

  <symbol dimension="m^2/s" name="D_3" value="0.00000000015"/>

  <symbol dimension="m^2/s" name="D_4" value="0.0000000006"/>

  <symbol dimension="1" name="alpha" value="2"/>

  <symbol dimension="mol/m^3" name="E_0" value="0.0455"/>

  <symbol dimension="mol/m^3" name="E_1" value="0.02275"/>

  <symbol dimension="mol/m^3" name="M_0" value="0.05"/>

  <symbol dimension="mol/m^3" name="S_0" value="100"/>

  <symbol dimension="mol/m^3" name="0" value="0"/>

  <symbol dimension="m^3/mol*s" name="k_1" value="690"/>

  <symbol dimension="m^3/mol*s" name="k_2" value="69000"/>

  <symbol dimension="m^3/mol*s" name="k_3" value="INF"/>

  <solver timeStep="0.0001" xsi:type="s:Implicit2D">
    <output name="response" stepCount="1000" xsi:type="s:Kinetic">
      <s:output name="currentDensity" xsi:type="s:CurrentDensity"/>
    </output>
    <output name="substanceConcentrations" stepCount="10000" xsi:type="s:Kinetic">
      <s:output name="concentrations" xsi:type="s:ConcentrationProfile"/>
      <s:output name="avgConcentrations" xsi:type="s:AveragedConcentration"/>
      <s:output medium="\Omega_1" name="avgConcInOmega_1" xsi:type="s:AveragedConcentration"/>
      <s:output medium="\Omega_2" name="avgConcInOmega_2" xsi:type="s:AveragedConcentration"/>
      <s:output medium="\Omega_3" name="avgConcInOmega_3" xsi:type="s:AveragedConcentration"/>
      <s:output medium="\Omega_4" name="avgConcInOmega_4" xsi:type="s:AveragedConcentration"/>
    </output>
    <s:axis from="r_0" stepCount="50" to="r_1" xsi:type="s:ConstantAxisPart"/>
    <s:axis from="r_1" stepCount="50" to="r_2" xsi:type="s:ConstantAxisPart"/>
    <s:axis from="z_0" stepCount="50" to="z_1" xsi:type="s:ConstantAxisPart"/>
    <s:axis from="z_1" stepCount="50" to="z_2" xsi:type="s:ConstantAxisPart"/>
    <s:axis from="z_2" stepCount="50" to="z_3" xsi:type="s:ConstantAxisPart"/>
    <s:axis from="z_3" stepCount="50" to="z_4" xsi:type="s:ConstantAxisPart"/>
    <s:stopCondition stepCount="1000" xsi:type="s:StopConditionValidAfter">
      <s:stopCondition lessThan="0.01" normalized="true" xsi:type="s:CurrentDensityGradient"/>
    </s:stopCondition>
    <s:stopCondition stepCount="500000000" xsi:type="s:FailIfAbove"/>
    <s:stopCondition xsi:type="s:FailIfInvalidConcentrations"/>
    <s:stopCondition error="0.000001" medium="\Omega_1" sum="E_0" xsi:type="s:FailISumOfConcentrationsNonConst">
      <s:substance>E_{ox}</s:substance>
      <s:substance>E_{red}</s:substance>
    </s:stopCondition>
    <s:stopCondition error="0.000001" medium="\Omega_2" sum="E_1" xsi:type="s:FailISumOfConcentrationsNonConst">
      <s:substance>E_{ox}</s:substance>
      <s:substance>E_{red}</s:substance>
    </s:stopCondition>
  </solver>

</model>

=== kape1395/biosensor.solver-2D/test/test-0100_cyl-trivial-vertical.xml
<?xml version="1.0" encoding="UTF-8"?>
<model
    xmlns  ="http://lt.5grupe.karolis/biosensor/model"
    xmlns:b="http://lt.5grupe.karolis/biosensor/model/bound"
    xmlns:r="http://lt.5grupe.karolis/biosensor/model/reaction"
    xmlns:s="http://lt.5grupe.karolis/biosensor/model/solver"
    xmlns:l="http://lt.5grupe.karolis/biosensor/model/listener"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://lt.5grupe.karolis/biosensor/model          ../src/libbiosensor-xml/Model.xsd
                        http://lt.5grupe.karolis/biosensor/model/bound    ../src/libbiosensor-xml/ModelBound.xsd
                        http://lt.5grupe.karolis/biosensor/model/reaction ../src/libbiosensor-xml/ModelReaction.xsd
                        http://lt.5grupe.karolis/biosensor/model/solver   ../src/libbiosensor-xml/ModelSolver.xsd
                        http://lt.5grupe.karolis/biosensor/model/listener ../src/libbiosensor-xml/ModelListener.xsd"
    coordinateSystem="Cylindrical">


    <axis name="r">
        <point position="r0"/>
        <point position="r1"/>
    </axis>
    <axis name="z">
        <point position="z0"/>
        <point position="z1"/>
    </axis>


    <substance name="S"/>


    <medium name="Diffusion">
        <substance name="S" diffusion="D_Diff_S" initial="0"/>
        <area top="z0" bottom="z1" left="r0" right="r1"/>
    </medium>

    <bound from="r0" to="r1" at="z0">
        <substance name="S" xsi:type="b:Constant" concentration="0"/>
    </bound>
    <bound from="r0" to="r1" at="z1">
        <substance name="S" xsi:type="b:Constant" concentration="S_0"/>
    </bound>



    <!-- Geometry -->
    <symbol name="r0"       value="0.0"     dimension="m"/>
    <symbol name="r1"       value="1.0E-3"  dimension="m"/>
    <symbol name="z0"       value="0.0"     dimension="m"/>
    <symbol name="z1"       value="1.0E-3"  dimension="m"/>
    <symbol name="D_Diff_S" value="1E-6"    dimension="m^2/s"/>
    <symbol name="S_0"      value="1E-8"    dimension="mol/cm^2"/>
    <symbol name="0"        value="0.0"     dimension="mol/cm^2"/>


    <solver xsi:type="s:Implicit2D" timeStep="1E-4">
        <s:axis from="r0" to="r1" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="z0" to="z1" xsi:type="s:ConstantAxisPart" stepCount="200"/>
    </solver>

</model>

=== kape1395/biosensor.solver-2D/src/bio_ers/test/bio_ers_model_tests-AllElems.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 !    This model has no particular meaning, just all XML element types are used here.
 !-->
<model
    xmlns  ="http://karolis.5grupe.lt/biosensor/model"
    xmlns:b="http://karolis.5grupe.lt/biosensor/model/bound"
    xmlns:r="http://karolis.5grupe.lt/biosensor/model/reaction"
    xmlns:s="http://karolis.5grupe.lt/biosensor/model/solver"
    xmlns:t="http://karolis.5grupe.lt/biosensor/model/transducer"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        http://karolis.5grupe.lt/biosensor/model            /usr/share/biosensor/Model.xsd
        http://karolis.5grupe.lt/biosensor/model/bound      /usr/share/biosensor/ModelBound.xsd
        http://karolis.5grupe.lt/biosensor/model/reaction   /usr/share/biosensor/ModelReaction.xsd
        http://karolis.5grupe.lt/biosensor/model/solver     /usr/share/biosensor/ModelSolver.xsd
        http://karolis.5grupe.lt/biosensor/model/transducer /usr/share/biosensor/ModelTransducer.xsd
        "
    coordinateSystem="Cylindrical">


    <axis name="r">
        <point position="r0"/>
        <point position="r1"/>
    </axis>
    <axis name="z">
        <point position="z0"/>
        <point position="z1"/>
    </axis>


    <substance name="S"/>
    <substance name="P"/>

    <reaction name="R_1" xsi:type="r:ReductionOxidation" rate="k_1">
        <r:substrate name="E_{ox}"/>
        <r:substrate name="S"/>
        <r:product name="E_{red}"/>
        <r:product name="E_{red}"/>
    </reaction>
    <reaction name="R_2" xsi:type="r:MichaelisMenten" substrate="AA" product="BB" V_max="jo" K_M="majo"/>

    <medium name="Omega_1">
        <substance name="S"         diffusion="D_1" initial="0"/>
        <substance name="M_{red}"   diffusion="D_1" initial="0"/>
        <reaction name="R_1"/>
        <reaction name="R_2"/>
        <area top="z_0" bottom="z_1" left="r_0" right="r_2"/>
        <area top="z_1" bottom="z_2" left="r_0" right="r_1"/>
    </medium>
    <medium name="Omega_2" diffusionRatio="alpha_2">
        <area top="z_1" bottom="z_2" left="r_2" right="r_3"/>
    </medium>


    <bound from="r_0" to="r_2" at="z_4" name="ExternalBound">
        <substance name="S"       xsi:type="b:Constant" concentration="S_0"/>
        <substance name="M_{ox}"  xsi:type="b:Wall"/>
    </bound>
    <bound from="r_0" to="r_2" at="z_1" name="BoundBetweenEnzymes">
        <substance name="M_{red}" xsi:type="b:Merge"/>
        <substance name="M_{red}" xsi:type="b:Null"/>
        <reaction name="R_3"/>
        <reaction name="R_2"/>
    </bound>

    <transducer name="electrode" xsi:type="t:CompositeElectrode">
        <t:transducer
            name="injectedElectrode"
            xsi:type="t:InjectedElectrode"
            medium="\Omega_2"
            reaction="R_2b"
        />
        <t:transducer
            name="streamElectrode"
            xsi:type="t:AmperometricElectrode"
            bound="BoundBetweenEnzymes"
            substance="M_{red}"
        />
    </transducer>

    <symbol name="r_0" value="0.0"      dimension="m"/>
    <symbol name="r_1" value="2.0E-7"   dimension="m"/>

    <solver xsi:type="s:Implicit2D" timeStep="1E-5">
        <output name="response" xsi:type="s:Kinetic" stepCount="10000">
            <s:output name="currentDensity" xsi:type="s:CurrentDensity"/>
        </output>
        <output name="substanceConcentrations" xsi:type="s:Kinetic" stepCount="100000">
            <s:output name="concentrations"     xsi:type="s:ConcentrationProfile" precision="12"/>
            <s:output name="avgConcentrations"  xsi:type="s:AveragedConcentration"/>
            <s:output name="avgConcInOmega_1"   xsi:type="s:AveragedConcentration" medium="\Omega_1"/>
        </output>
        <s:axis from="z_2" to="z_3" xsi:type="s:ConstantAxisPart" stepCount="50"/>
        <s:axis from="z_3" to="z_4" xsi:type="s:ConstantAxisPart" stepCount="50"/>
        <s:stopCondition xsi:type="s:StopConditionValidAfter" stepCount="1000">
            <s:stopCondition xsi:type="s:CurrentDensityGradient" lessThan="0.01" normalized="true"/>
        </s:stopCondition>
        <s:stopCondition xsi:type="s:FailIfAbove" stepCount="500000000"/>
        <s:stopCondition xsi:type="s:FailIfInvalidConcentrations"/>
        <s:stopCondition error="0.00001" medium="\Omega_1" sum="E_0" xsi:type="s:FailISumOfConcentrationsNonConst">
            <s:substance>E_{ox}</s:substance>
            <s:substance>E_{red}</s:substance>
        </s:stopCondition>
    </solver>

</model>

=== kape1395/biosensor.solver-2D/src/libbiosensor-xml/Model-example-2D.xml
<?xml version="1.0" encoding="UTF-8"?>
<model
    xmlns  ="http://lt.5grupe.karolis/biosensor/model"
    xmlns:b="http://lt.5grupe.karolis/biosensor/model/bound"
    xmlns:r="http://lt.5grupe.karolis/biosensor/model/reaction"
    xmlns:s="http://lt.5grupe.karolis/biosensor/model/solver"
    xmlns:l="http://lt.5grupe.karolis/biosensor/model/listener"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://lt.5grupe.karolis/biosensor/model          Model.xsd
                        http://lt.5grupe.karolis/biosensor/model/bound    ModelBound.xsd
                        http://lt.5grupe.karolis/biosensor/model/reaction ModelReaction.xsd
                        http://lt.5grupe.karolis/biosensor/model/solver   ModelSolver.xsd
                        http://lt.5grupe.karolis/biosensor/model/listener ModelListener.xsd"
    coordinateSystem="Cartesian">

    <axis name="x">
        <point position="x1"/>
        <point position="x2"/>
        <point position="x3"/>
    </axis>
    <axis name="y">
        <point position="y1"/>
        <point position="y2"/>
        <point position="y3"/>
        <point position="y4"/>
    </axis>

    <substance name="S"/>
    <substance name="P"/>


    <medium name="Enzyme">
        <substance name="S" diffusion="D_Enz_S" initial="S_0"/>
        <substance name="P" diffusion="D_Enz_P" initial="P_0"/>
        <reaction xsi:type="r:MichaelisMenten"
            substrate="S"
            product="P"
            V_max="V_max"
            K_M="K_M"
        />
        <area top="y1" bottom="y2" left="x1" right="x2"/>
        <area top="y2" bottom="y3" left="x1" right="x3"/>
    </medium>
    <medium name="PerforatedMembrane">
        <area top="y1" bottom="y2" left="x2" right="x3"/>
    </medium>
    <medium name="SelectiveMembrane">
        <substance name="P" diffusion="D_Sel_P" initial="P_0"/>
        <area top="y3" bottom="y4" left="x1" right="x3"/>
    </medium>

    <bound from="x1" to="x2" at="y1">
        <substance name="S" xsi:type="b:Constant" concentration="S_Ext"/>
        <substance name="P" xsi:type="b:Constant" concentration="P_Ext"/>
    </bound>
    <bound from="y1" to="y3" at="x1">
        <substance name="S" xsi:type="b:Wall"/>
    </bound>
    <bound from="y1" to="y4" at="x1">
        <substance name="P" xsi:type="b:Wall"/>
    </bound>
    <bound from="y2" to="y3" at="x3">
        <substance name="S" xsi:type="b:Wall"/>
    </bound>
    <bound from="y2" to="y4" at="x3">
        <substance name="P" xsi:type="b:Wall"/>
    </bound>
    <bound from="x1" to="x3" at="y4">
        <substance name="P" xsi:type="b:Constant" concentration="E_0"/>
    </bound>

    <electrode name="Electrode">
        <substrate substrate="P"/>
        <position from="x1" to="x3" at="y4"/>
    </electrode>

    <symbol name="S_Ext"    value="7.5E-7"  dimension="mol/cm^2"/>
    <symbol name="P_Ext"    value="0.0"     dimension="mol/cm^2"/>
    <symbol name="S_0"      value="0.0"     dimension="mol/cm^2"/>
    <symbol name="P_0"      value="0.0"     dimension="mol/cm^2"/>
    <symbol name="E_0"      value="0.0"     dimension="mol/cm^2"/>
    <symbol name="V_max"    value="1E-8"    dimension="mol/s"/>
    <symbol name="K_M"      value="1E-8"    />
    <symbol name="D_Enz_S"  value="1E-6"    dimension="m^2/s"/>
    <symbol name="D_Enz_P"  value="1E-6"    dimension="m^2/s"/>
    <symbol name="D_Sel_P"  value="1E-6"    dimension="m^2/s"/>
    <symbol name="x1"       value="0.0"     dimension="m"/>
    <symbol name="x2"       value="1.0E-5"  dimension="m"/>
    <symbol name="x3"       value="1.01E-3" dimension="m"/>
    <symbol name="y1"       value="0.0"     dimension="m"/>
    <symbol name="y2"       value="1.0E-3"  dimension="m"/>
    <symbol name="y3"       value="1.2E-3"  dimension="m"/>
    <symbol name="y4"       value="1.4E-3"  dimension="m"/>

    <solver xsi:type="s:Implicit2D" timeStep="5E-9">
        <s:axis from="x1" to="x2" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="x2" to="x3" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="y1" to="y2" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="y2" to="y3" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="y3" to="y4" xsi:type="s:ConstantAxisPart" stepCount="200"/>
    </solver>

    <listener xsi:type="l:InvokeEvery" iterations="100">
        <l:listener xsi:type="l:StopAfter" iterations="3000"/>
    </listener>
    
</model>
