=== kape1395/biosensor.solver-2D/src/libbiosensor-xml/Model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    targetNamespace ="http://lt.5grupe.karolis/biosensor/model"
    xmlns           ="http://lt.5grupe.karolis/biosensor/model"
    xmlns:xs        ="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    
    
    
    <xs:element name="model" type="Model"/>
    
    
    
    <xs:complexType name="Model">
        <xs:sequence>
            <xs:element name="axis"         type="Axis"         minOccurs="1" maxOccurs="2"/>
            <xs:element name="substance"    type="Substance"    minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="medium"       type="Medium"       minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="bound"        type="Bound"        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="transducer"   type="Transducer"   minOccurs="0" maxOccurs="1"/>
            <xs:element name="symbol"       type="Symbol"       minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="solver"       type="Solver"       minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="coordinateSystem" type="CoordinateSystem" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Axis">
        <xs:sequence>
            <xs:element name="point" type="AxisPoint" minOccurs="2" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="AxisName" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="AxisPoint">
        <xs:attribute name="position" type="SymbolName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Substance">
        <xs:attribute name="name" type="SubstanceName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Medium">
        <xs:sequence>
            <xs:element name="substance" type="MediumSubstance" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="reaction"  type="MediumReaction"  minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="area"      type="MediumArea"      minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="MediumName" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="MediumSubstance">
        <xs:attribute name="name"       type="SubstanceName" use="required"/>
        <xs:attribute name="diffusion"  type="SymbolName"    use="optional"/>
        <xs:attribute name="initial"    type="SymbolName"    use="required"/>
    </xs:complexType>
    
    <xs:complexType name="MediumReaction" abstract="true">
    </xs:complexType>
    
    <xs:complexType name="MediumArea">
        <xs:attribute name="top"    type="SymbolName" use="optional"/>
        <xs:attribute name="bottom" type="SymbolName" use="optional"/>
        <xs:attribute name="left"   type="SymbolName" use="optional"/>
        <xs:attribute name="right"  type="SymbolName" use="optional"/>
        <xs:attribute name="from"   type="SymbolName" use="optional"/>
        <xs:attribute name="to"     type="SymbolName" use="optional"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Bound">
        <xs:sequence>
            <xs:element name="substance" type="BoundSubstance" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name"   type="BoundName"    use="optional"/>
        <xs:attribute name="from"   type="SymbolName"   use="optional"/>
        <xs:attribute name="to"     type="SymbolName"   use="optional"/>
        <xs:attribute name="at"     type="SymbolName"   use="required"/>
    </xs:complexType>
    
    <xs:complexType name="BoundSubstance" abstract="true">
        <xs:attribute name="name" type="SubstanceName" use="required"/>
    </xs:complexType>
    
    

    <xs:complexType name="Transducer" abstract="true">
        <xs:attribute name="name" type="TransducerName" use="required"/>
    </xs:complexType>
    
    
    
    <xs:complexType name="Symbol">
        <xs:attribute name="name"       type="SymbolName" use="required"/>
        <xs:attribute name="value"      type="xs:double"  use="required"/>
        <xs:attribute name="dimension"  type="xs:string"  use="optional"/>
    </xs:complexType>
    
    
    <xs:complexType name="Solver" abstract="true">
        <xs:sequence>
            <xs:element name="output" type="SolverOutput" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SolverOutput" abstract="true">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    

    <xs:simpleType name="CoordinateSystem">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Cartesian"/>
            <xs:enumeration value="Cylindrical"/>
            <xs:enumeration value="Linear"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="SubstanceName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="MediumName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="AxisName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="BoundName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="TransducerName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="SymbolName">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
</xs:schema>

=== kape1395/biosensor.solver-2D/tmp-injected_electrode.xml
<?xml version="1.0" encoding="UTF-8"?>
<model
    xmlns  ="http://lt.5grupe.karolis/biosensor/model"
    xmlns:b="http://lt.5grupe.karolis/biosensor/model/bound"
    xmlns:r="http://lt.5grupe.karolis/biosensor/model/reaction"
    xmlns:s="http://lt.5grupe.karolis/biosensor/model/solver"
    xmlns:t="http://lt.5grupe.karolis/biosensor/model/transducer"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        http://lt.5grupe.karolis/biosensor/model            src/libbiosensor-xml/Model.xsd
        http://lt.5grupe.karolis/biosensor/model/bound      src/libbiosensor-xml/ModelBound.xsd
        http://lt.5grupe.karolis/biosensor/model/reaction   src/libbiosensor-xml/ModelReaction.xsd
        http://lt.5grupe.karolis/biosensor/model/solver     src/libbiosensor-xml/ModelSolver.xsd
        http://lt.5grupe.karolis/biosensor/model/transducer src/libbiosensor-xml/ModelTransducer.xsd
        "
    coordinateSystem="Cylindrical">


    <axis name="r">
        <point position="r_0"/>
        <point position="r_1"/>
        <point position="r_2"/>
    </axis>
    <axis name="z">
        <point position="z_0"/>
        <point position="z_1"/>
        <point position="z_2"/>
        <point position="z_3"/>
    </axis>


    <substance name="S"/>
    <substance name="P"/>
    <substance name="E_{ox}"/>
    <substance name="E_{red}"/>
    <substance name="M_{ox}"/>
    <substance name="M_{red}"/>


    <medium name="\Omega_1">
        <substance name="S"       diffusion="D_Diff_S" initial="0"/>
        <substance name="P"       diffusion="D_Diff_S" initial="0"/>
        <substance name="M_{ox}"  diffusion="D_Diff_M" initial="0"/>
        <substance name="M_{red}" diffusion="D_Diff_M" initial="0"/>
        <area top="z_0" bottom="z_1" left="r_0" right="r_2"/>
    </medium>
    <medium name="\Omega_2">
        <substance name="S"       diffusion="D_Enz_S" initial="0"/>
        <substance name="P"       diffusion="D_Enz_S" initial="0"/>
        <substance name="E_{ox}"                      initial="E_0"/>
        <substance name="E_{red}"                     initial="0"/>
        <substance name="M_{ox}"  diffusion="D_Enz_M" initial="0"/>
        <substance name="M_{red}" diffusion="D_Enz_M" initial="0"/>
        <reaction xsi:type="r:ReductionOxidation" rate="k_1">
            <r:substrate name="E_{ox}"/>
            <r:substrate name="S"/>
            <r:product name="E_{red}"/>
            <r:product name="P"/>
        </reaction>
        <reaction xsi:type="r:ReductionOxidation" rate="k_2">
            <r:substrate name="E_{red}"/>
            <r:substrate name="M_{ox}"/>
            <r:product name="E_{ox}"/>
            <r:product name="M_{red}"/>
        </reaction>
        <area top="z_1" bottom="z_2" left="r_0" right="r_2"/>
    </medium>
    <medium name="\Omega_3">
        <substance name="S"       diffusion="D_Enz_S" initial="0"/>
        <substance name="P"       diffusion="D_Enz_S" initial="0"/>
        <substance name="E_{ox}"                      initial="E_0"/>
        <substance name="E_{red}"                     initial="0"/>
        <substance name="M_{ox}"  diffusion="D_Enz_M" initial="0"/>
        <substance name="M_{red}" diffusion="D_Enz_M" initial="0"/>
        <reaction xsi:type="r:ReductionOxidation" rate="k_1">
            <r:substrate name="E_{ox}"/>
            <r:substrate name="S"/>
            <r:product name="E_{red}"/>
            <r:product name="P"/>
        </reaction>
        <reaction xsi:type="r:ReductionOxidation" rate="k_2">
            <r:substrate name="E_{red}"/>
            <r:substrate name="M_{ox}"/>
            <r:product name="E_{ox}"/>
            <r:product name="M_{red}"/>
        </reaction>
        <area top="z_2" bottom="z_3" left="r_0" right="r_1"/>
    </medium>


    <!--bound from="z_0" to="z_3" at="r_0">
        <substance name="S"       xsi:type="b:Wall"/>
        <substance name="M_{ox}"  xsi:type="b:Wall"/>
        <substance name="M_{red}" xsi:type="b:Wall"/>
    </bound-->
    <bound from="z_1" to="z_3" at="r_0">
        <substance name="E_{ox}"  xsi:type="b:Wall"/>
        <substance name="E_{red}" xsi:type="b:Wall"/>
    </bound>
    <!--bound from="z_0" to="z_2" at="r_2">
        <substance name="S"       xsi:type="b:Wall"/>
        <substance name="M_{ox}"  xsi:type="b:Wall"/>
        <substance name="M_{red}" xsi:type="b:Wall"/>
    </bound>
    <bound from="z_1" to="z_2" at="r_2">
        <substance name="E_{ox}"  xsi:type="b:Wall"/>
        <substance name="E_{red}" xsi:type="b:Wall"/>
    </bound-->
    <bound from="r_0" to="r_2" at="z_0">
        <substance name="S"       xsi:type="b:Constant" concentration="S_0"/>
        <substance name="P"       xsi:type="b:Constant" concentration="0"/>
        <substance name="M_{ox}"  xsi:type="b:Constant" concentration="M_0"/>
        <substance name="M_{red}" xsi:type="b:Constant" concentration="0"  />
    </bound>
    <!--bound from="r_0" to="r_1" at="z_3">
        <substance name="S"       xsi:type="b:Wall"/>
        <substance name="E_{ox}"  xsi:type="b:Wall"/>
        <substance name="E_{red}" xsi:type="b:Wall"/>
        <substance name="M_{ox}"  xsi:type="b:Wall"/>
        <substance name="M_{red}" xsi:type="b:Wall"/>
    </bound-->


    <transducer
        name="electrode"
        xsi:type="t:InjectedElectrode"
        medium="\Omega_2"
        substance="M_{red}"
    />


    <!-- Geometry -->
    <symbol name="r_0" value="0.0"      dimension="m"/>
    <symbol name="r_1" value="1.0E-7"   dimension="m"/>
    <symbol name="r_2" value="1.0E-6"   dimension="m"/>
    <symbol name="z_0" value="0.0"      dimension="m"/>
    <symbol name="z_1" value="3.000E-4" dimension="m"/>
    <symbol name="z_2" value="3.004E-4" dimension="m"/>
    <symbol name="z_3" value="3.104E-4" dimension="m"/>

    <!-- Diffusion coefficients -->
    <symbol name="D_Enz_S"  value="3.0E-4" dimension="m^2/s"/>
    <symbol name="D_Enz_M"  value="3.0E-4" dimension="m^2/s"/>
    <symbol name="D_Diff_S" value="6.0E-4" dimension="m^2/s"/>
    <symbol name="D_Diff_M" value="6.0E-4" dimension="m^2/s"/>

    <!-- Concentrations -->
    <symbol name="E_0" value="3.0E-3" dimension="mol/m^3"/>
    <symbol name="M_0" value="1.0E-1" dimension="mol/m^3"/>
    <symbol name="S_0" value="1.0E2"  dimension="mol/m^3"/>
    <symbol name="0"   value="0.0"    dimension="mol/m^3"/>

    <!-- Reaction rates -->
    <symbol name="k_1" value="1E7"  dimension="mol/m^3 s"/>
    <symbol name="k_2" value="1E10" dimension="mol/m^3 s"/>


    <solver xsi:type="s:Implicit2D" timeStep="1E-9">
        <output name="kinetic" xsi:type="s:Kinetic" stepCount="1">
            <s:output name="concentrations" xsi:type="s:ConcentrationProfile"/>
            <s:output name="currentDensity" xsi:type="s:CurrentDensity"/>
        </output>
        <!--output name="steadyState" xsi:type="s:SteadyState">
            <s:output name="profile"        xsi:type="s:ConcentrationProfile"/>
            <s:output name="density"        xsi:type="s:CurrentDensity"/>
            < ! - -utput name="halfTime"       xsi:type="s:SteadyStateHalfTime"/- - >
        </output-->
        <s:axis from="r_0" to="r_1" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="r_1" to="r_2" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="z_0" to="z_1" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="z_1" to="z_2" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="z_2" to="z_3" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:stopCondition
            xsi:type="s:StopConditionValidAfter"
            stepCount="1000">
            <!--s:stopCondition
                xsi:type="s:CurrentDensityGradient"
                lessThan="0.0001"
            /-->
        </s:stopCondition>
        <s:stopCondition xsi:type="s:FailIfAbove" stepCount="3"/>
    </solver>

</model>

=== kape1395/biosensor.solver-2D/test/test-1101-cyl-perforated_membrane_pseudo1D.xml
<?xml version="1.0" encoding="UTF-8"?>
<model
    xmlns  ="http://lt.5grupe.karolis/biosensor/model"
    xmlns:b="http://lt.5grupe.karolis/biosensor/model/bound"
    xmlns:r="http://lt.5grupe.karolis/biosensor/model/reaction"
    xmlns:s="http://lt.5grupe.karolis/biosensor/model/solver"
    xmlns:t="http://lt.5grupe.karolis/biosensor/model/transducer"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        http://lt.5grupe.karolis/biosensor/model            ../src/libbiosensor-xml/Model.xsd
        http://lt.5grupe.karolis/biosensor/model/bound      ../src/libbiosensor-xml/ModelBound.xsd
        http://lt.5grupe.karolis/biosensor/model/reaction   ../src/libbiosensor-xml/ModelReaction.xsd
        http://lt.5grupe.karolis/biosensor/model/solver     ../src/libbiosensor-xml/ModelSolver.xsd
        http://lt.5grupe.karolis/biosensor/model/transducer ../src/libbiosensor-xml/ModelTransducer.xsd
        "
    coordinateSystem="Cartesian">


    <axis name="x">
        <point position="x_0"/>
        <point position="x_1"/>
    </axis>
    <axis name="y">
        <point position="z_0"/>
        <point position="z_1"/>
        <point position="z_2"/>
        <point position="z_4"/>
    </axis>


    <substance name="S"/>
    <substance name="P"/>


    <medium name="Omega_1 (selective membrane)">
        <substance name="P" diffusion="D_1" initial="0"/>
        <area top="z_1" bottom="z_0" left="x_0" right="x_1"/>
    </medium>
    <medium name="Omega_2 (enzyme)">
        <substance name="S" diffusion="D_2" initial="0"/>
        <substance name="P" diffusion="D_2" initial="0"/>
        <reaction xsi:type="r:MichaelisMenten" V_max="V_max_2" K_M="K_M" substrate="S" product="P"/>
        <area top="z_2" bottom="z_1" left="x_0" right="x_1"/>
    </medium>
    <medium name="Omega^*_3 (homogenized perforated membrane)">
        <substance name="S" diffusion="D^*_3" initial="0"/>
        <substance name="P" diffusion="D^*_3" initial="0"/>
        <reaction xsi:type="r:MichaelisMenten" V_max="V_max_3" K_M="K_M" substrate="S" product="P"/>
        <area top="z_4" bottom="z_2"  left="x_0" right="x_1"/>
    </medium>


    <bound from="x_0" to="x_1" at="z_0" name="electrodeSurface">
        <substance name="P" xsi:type="b:Constant" concentration="0"/>
    </bound>
    <bound from="x_0" to="x_1" at="z_4">
        <substance name="S" xsi:type="b:Constant" concentration="S_0"/>
        <substance name="P" xsi:type="b:Constant" concentration="0"/>
    </bound>


    <transducer
        name="electrode"
        xsi:type="t:AmperometricElectrode"
        bound="electrodeSurface"
        substance="P"
    />

    <!-- Geometry -->
    <symbol name="x_0"   value="0.0"     dimension="m"/>
    <symbol name="x_1"   value="1.0"     dimension="m"/>
    <symbol name="z_0"   value="0.0"     dimension="m"/>
    <symbol name="z_1"   value="2E-6"    dimension="m"/>
    <symbol name="z_2"   value="4E-6"    dimension="m"/>
    <symbol name="z_4"   value="14E-6"   dimension="m"/>

    <!-- Diffusion coefficients -->
    <symbol name="D_1"      value="1E-12"                   dimension="m^2/s"/>
    <symbol name="D_2"      value="3E-10"                   dimension="m^2/s"/>
    <symbol name="D^*_3"    value="4.5549174604878327E-12"  dimension="m^2/s"/>

    <!-- Concentrations -->
    <symbol name="S_0"  value="1E-4"    dimension="mol/m^3"/>
    <symbol name="0"    value="0.0"     dimension="mol/m^3"/>

    <!-- Reaction parameters -->
    <symbol name="V_max_2"  value="1E-2"  dimension="mol/m^3*s"/>
    <symbol name="V_max_3"  value="1E-4"  dimension="mol/m^3*s"/>
    <symbol name="K_M"      value="1E-1"  dimension="mol/m^3"/>

    
    <solver xsi:type="s:Implicit2D" timeStep="1E-4">
        <output name="kinetic" xsi:type="s:Kinetic" stepCount="1000">
            <s:output name="concentrations" xsi:type="s:ConcentrationProfile"/>
            <s:output name="currentDensity" xsi:type="s:CurrentDensity"/>
        </output>
        <s:axis from="x_0" to="x_1" xsi:type="s:ConstantAxisPart" stepCount="2"/>
        <s:axis from="z_0" to="z_1" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="z_1" to="z_2" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:axis from="z_2" to="z_4" xsi:type="s:ConstantAxisPart" stepCount="200"/>
        <s:stopCondition xsi:type="s:FailIfAbove" stepCount="1000000"/>
    </solver>

</model>

=== kape1395/biosensor.solver-2D/src/libbiosensor-xml/Model-example-1D.xml
<?xml version="1.0" encoding="UTF-8"?>
<model
    xmlns  ="http://lt.5grupe.karolis/biosensor/model"
    xmlns:b="http://lt.5grupe.karolis/biosensor/model/bound"
    xmlns:r="http://lt.5grupe.karolis/biosensor/model/reaction"
    xmlns:s="http://lt.5grupe.karolis/biosensor/model/solver"
    xmlns:l="http://lt.5grupe.karolis/biosensor/model/listener"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://lt.5grupe.karolis/biosensor/model          Model.xsd
                        http://lt.5grupe.karolis/biosensor/model/bound    ModelBound.xsd
                        http://lt.5grupe.karolis/biosensor/model/reaction ModelReaction.xsd
                        http://lt.5grupe.karolis/biosensor/model/solver   ModelSolver.xsd
                        http://lt.5grupe.karolis/biosensor/model/listener ModelListener.xsd"
    coordinateSystem="Linear">

    <axis name="x">
        <point position="x1"/>
        <point position="x2"/>
        <point position="x3"/>
        <point position="x4"/>
    </axis>

    <substance name="S"/>
    <substance name="P"/>

    <medium name="PerforatedMembrane">
        <substance name="S" diffusion="D_Per_S" initial="S_0"/>
        <substance name="P" diffusion="D_Per_P" initial="P_0"/>
        <reaction xsi:type="r:MichaelisMenten"
            substrate="S"
            product="P"
            V_max="V_max_Per"
            K_M="K_M_Per"
        />
        <area from="x1" to="x2"/>
    </medium>
    <medium name="Enzyme">
        <substance name="S" diffusion="D_Enz_S" initial="S_0"/>
        <substance name="P" diffusion="D_Enz_P" initial="P_0"/>
        <reaction xsi:type="r:MichaelisMenten"
            substrate="S"
            product="P"
            V_max="V_max_Enz"
            K_M="K_M_Enz"
        />
        <area from="x2" to="x3"/>
    </medium>
    <medium name="SelectiveMembrane">
        <substance name="P" diffusion="D_Sel_P" initial="P_0"/>
        <area from="x3" to="x4"/>
    </medium>

    <bound at="x1">
        <substance name="S" xsi:type="b:Constant" concentration="S_Ext" initial="S_Ext"/>
        <substance name="P" xsi:type="b:Constant" concentration="P_Ext" initial="P_Ext"/>
    </bound>
    <bound at="x4">
        <substance name="P" xsi:type="b:Constant" concentration="E_0" initial="E_0"/>
    </bound>

    <electrode name="Electrode">
        <substrate substrate="P"/>
        <position at="x4"/>
    </electrode>

    <symbol name="S_Ext"        value="7.5E-7"  dimension="mol/cm^2"/>
    <symbol name="P_Ext"        value="0.0"     dimension="mol/cm^2"/>
    <symbol name="S_0"          value="0.0"     dimension="mol/cm^2"/>
    <symbol name="P_0"          value="0.0"     dimension="mol/cm^2"/>
    <symbol name="E_0"          value="0.0"     dimension="mol/cm^2"/>
    <symbol name="V_max_Enz"    value="1E-8"    dimension="mol/s"/>
    <symbol name="V_max_Per"    value="1E-8"    dimension="mol/s"/>
    <symbol name="K_M_Enz"      value="1E-8"    />
    <symbol name="K_M_Per"      value="1E-8"    />
    <symbol name="D_Enz_S"      value="1E-6"    dimension="m^2/s"/>
    <symbol name="D_Enz_P"      value="1E-6"    dimension="m^2/s"/>
    <symbol name="D_Sel_P"      value="1E-6"    dimension="m^2/s"/>
    <symbol name="x1"           value="0.0"     dimension="m"/>
    <symbol name="x2"           value="1.0E-3"  dimension="m"/>
    <symbol name="x3"           value="1.2E-3"  dimension="m"/>
    <symbol name="x4"           value="1.4E-3"  dimension="m"/>

    <solver xsi:type="s:Explicit1D" timeStep="5E-9">
        <s:axis from="x1" to="x2" xsi:type="s:ConstantAxisPart" stepCount="50"/>
        <s:axis from="x2" to="x3" xsi:type="s:ConstantAxisPart" stepCount="50"/>
    </solver>

</model>
